# This workflow is used to test the GitHub action publish-kedro-viz

name: Test publish-kedro-viz

permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches:
      - "*"
    paths-ignore:
      - "*.md"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Project Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy Kedro-Viz to GH Pages
        uses: kedro-org/publish-kedro-viz@v1
        with:
          publishing_source: 'branch'
